name: CI12

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Xcode 12.4 iPhone 12
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
    - name: Build
      run: xcodebuild clean build -workspace ThinkersDiary.xcworkspace -scheme "ThinkersDiary" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 12" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
  
